
openapi: 3.0.3
info:
  title: Rabbit challenge
  description: Shows you how deep the rabbit-hole goes
  termsOfService: http://swagger.io/terms/
  contact:
    email: kucherenko.xandr@gmail.com
  license:
    name: ISC
    url: https://opensource.org/licenses/ISC
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: /api/v1
 
paths:
  /findAnswers:
    post:
      description: |
        find the answers to the question!
      operationId: findAnswers
      x-eov-operation-id: findAnswers
      x-eov-operation-handler: findAnswers
      requestBody:
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                anagram:
                  type: string
                  minLength: 1
                matches:
                  type: array
                  items:
                    type: string
                    pattern: '^\w{32}$'
                  minItems: 1
                wordlist:
                  type: string
                  format: binary
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswersResponse'
 
components:
  schemas:
    AnswersResponse:
      type: object
      additionalProperties: false
      required:
        - list
      properties:
        list:
          type: object